name: Databricks CI
on: [push, pull_request]
jobs: 
  run-databricks-ci: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python -V
      - run: pip install virtualenv
      - run: virtualenv venv
      - run: source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Uninstall py as it is not needed
        run: echo "y" | pip uninstall py

      - name: Run PyTest
        env: 
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_CLUSTER_ID: ${{ secrets.DATABRICKS_CLUSTER_ID }}
          DATABRICKS_WORKSPACE_ORG_ID: ${{ secrets.DATABRICKS_WORKSPACE_ORG_ID }}
        run: |
          pytest --log-cli-level=DEBUG functions/ --junitxml=unit-testresults.xml

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: unit-testresults.xml